rules:
    indentation:
        - 2
        -
            size: 2
    class-name-format: 0
    property-sort-order: 0
    variable-name-format: 0
    hex-notation: 0
    mixin-name-format: 0
    function-name-format: 0
